name: test-e2e

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        type: string
        required: false

jobs:
  update-initial-status:
    runs-on: ubuntu-22.04
    steps:
      - uses: mattermost/actions/delivery/update-commit-status@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          repository_full_name: ${{ github.repository }}
          commit_sha: ${{ inputs.commit_sha || github.sha }}
          context: E2E Tests/e2e
          description: "E2E tests running for ${{ inputs.commit_sha || github.sha }}"
          status: pending

  e2e:
    runs-on: ubuntu-22.04
    needs: update-initial-status
    steps:
      - run: |
          echo "This is an e2e test from the PR"
          echo "Such good tests"
          echo "Adding a new super line from fork"
          echo "Adding another new super line from fork"

  # We need to duplicate here in order to set the proper commit status
  # https://mattermost.atlassian.net/browse/CLD-5815
  update-failure-final-status:
    runs-on: ubuntu-22.04
    if: failure() || cancelled()
    needs:
      - e2e
    steps:
      - uses: mattermost/actions/delivery/update-commit-status@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          repository_full_name: mattermost/test-public-project
          commit_sha: ${{ inputs.commit_sha || github.sha }}
          context: E2E Tests/e2e
          description: "E2E tests running for ${{ inputs.commit_sha || github.sha }}"
          status: failure

  # https://mattermost.atlassian.net/browse/CLD-5815
  update-success-final-status:
    runs-on: ubuntu-22.04
    if: success()
    needs:
      - e2e
    steps:
      - uses: mattermost/actions/delivery/update-commit-status@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          repository_full_name: mattermost/test-public-project
          commit_sha: ${{ inputs.commit_sha || github.sha }}
          context: E2E Tests/e2e
          description: "E2E tests running for ${{ inputs.commit_sha || github.sha }}"
          status: success
